version: '3'
services:
    api:
        container_name: shopapp-api
        restart: always
        build: .
        depends_on:
            - mongodb
        links:
            - mongodb
        ports:
            - '8081:8081'
        volumes:
            - ./:/opt/app
            - /opt/app/node_modules
    mongodb:
        container_name: mongo
        restart: always
        image: mongo
        ports:
            - '27017:27017'
        logging:
            driver: 'none'
