# version: '1.0.0'

services:
    api:
        container_name: shopapp-api
        restart: always
        build: .
        depends_on:
            - mongo
        links:
            - mongo
        ports:
            - '8000:8000'
        volumes:
            - ./:/opt/app
            - /opt/app/node_modules
    mongo:
        container_name: mongo
        restart: always
        image: mongo
        ports:
            - '27017:27017'
        logging:
            driver: 'none'
